language: java

jdk:
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2

after_success:
  - ./gradlew jacocoTestReport coveralls
  - ./config/build-integration-branch.sh 
